import * as config from '../config'
import { generateRoot } from './generate-root'
import { generateScale } from './generate-scale'
import { generateTailwind } from './generate-tailwind'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const tailwind = generateTailwind(config)
const root = generateRoot(config)
const scale = generateScale()

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

const tailwindcss = [banner, tailwind, scale]
const rootcss = [banner, root]

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const cssDir = path.resolve(__dirname, '../css')

// Ensure the directory exists
if (!fs.existsSync(cssDir)) {
  fs.mkdirSync(cssDir, { recursive: true })
}

fs.writeFileSync(path.join(cssDir, 'tailwind.css'), tailwindcss.join('\n\n'))
fs.writeFileSync(path.join(cssDir, 'root.css'), rootcss.join('\n\n'))

console.log('✓ Style config generated successfully')
